apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "awwesome.fullname" . }}-generator
  labels:
    app: awwesome
    {{- include "awwesome.labels" . | nindent 4 }}
    {{- if .Values.generator.labels }}
    {{- with .Values.generator.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  schedule: {{ .Values.generator.schedule | default "0 */12 * * *" }}
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      activeDeadlineSeconds: {{ .Values.generator.activeDeadlineSeconds | default 360 }}
      parallelism: 1
      template:
        spec:
          activeDeadlineSeconds: {{ .Values.generator.activeDeadlineSeconds | default 360 }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.generator.image.repository | default "mkitzmann/awwesome"  }}:{{ .Values.generator.image.tag | default "latest" }}"
              command: ["/bin/bash"]
              workingDir: "/usr/src/app"
              args:
                - -c
                - echo "TOKEN_GITHUB=$(echo -n $GITHUB_TOKEN)" > /usr/src/app/.env && cd /usr/src/app/ && npm install && npm update && npm run build && rm -rf {{ .Values.web.mountPath | default "/usr/share/nginx/html" }}/* && cp -r dist/* {{ .Values.web.mountPath | default "/usr/share/nginx/html" }} && echo "done"
              volumeMounts:
                - name: {{ include "awwesome.fullname" . }}-volume
                  mountPath: {{ .Values.web.mountPath | default "/usr/share/nginx/html" }}
              env:
                - name: REQUEST_DELAY
                  value: "{{ (.Values.generator.config).request_delay | default "0"}}"
                - name: CHUNK_SIZE
                  value: "{{ (.Values.generator.config).chunk_size | default "20"}}"
                - name: LOW_COMMIT_COUNT
                  value: "{{ (.Values.generator.config).low_commit_count | default "0"}}"
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.generator.secret.name | default "awwesome" }}
                      key: {{ .Values.generator.secret.key | default "github_token" }}
              {{- if .Values.generator.resources }}
              resources:
              {{- toYaml .Values.generator.resources | nindent 16 }}
              {{- end }}
          restartPolicy: {{ .Values.generator.restartPolicy | default "OnFailure" }}
          {{- with .Values.generator.nodeSelector }}
          nodeSelector:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.generator.affinity }}
          affinity:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.generator.tolerations }}
          tolerations:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          terminationGracePeriodSeconds: {{ .Values.generator.terminationGracePeriodSeconds | default 10 }}
          volumes:
            - name: {{ include "awwesome.fullname" . }}-volume
              persistentVolumeClaim:
                claimName: {{ include "awwesome.fullname" . }}-pvc
