apiVersion: v1
kind: Service
metadata:
  name: {{ include "awwesome.fullname" . }}
  labels:
    {{- include "awwesome.labels" . | nindent 4 }}
{{- if .Values.web.labels }}
{{- with .Values.web.labels }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
spec:
  ports:
    - name: {{ include "awwesome.fullname" . }}
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    {{- include "awwesome.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
