apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "awwesome.fullname" . }}-generator
  labels:
    app: awwesome
    {{- include "awwesome.labels" . | nindent 4 }}
    {{- if .Values.generator.labels }}
    {{- with .Values.generator.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  schedule: {{ .Values.generator.schedule | default "0 */12 * * *" }}
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.generator.image.repository | default "mkitzmann/awwesome"  }}:{{ .Values.generator.image.tag | default "latest" }}"
              command: ["/bin/sh"]
              workingDir: "/usr/src/app"
              args:
                - -c
                - |
                  echo "TOKEN_GITHUB=$(echo -n $GITHUB_TOKEN)" > /usr/src/app/.env
                  cd /usr/src/app/
                  npm run build
                  rm -rf {{ .Values.web.mountPath | default "/usr/share/nginx/html" }}/*
                  cp -r dist/* {{ .Values.web.mountPath | default "/usr/share/nginx/html" }}
              volumeMounts:
                - name: {{ include "awwesome.fullname" . }}-volume
                  mountPath: {{ .Values.web.mountPath | default "/usr/share/nginx/html" }}
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.generator.secret.name | default "awwesome" }}
                      key: {{ .Values.generator.secret.key | default "github_token" }}
              {{- if .Values.generator.resources }}
              resources:
              {{- toYaml .Values.generator.resources | nindent 16 }}
              {{- end }}
          restartPolicy: {{ .Values.generator.restartPolicy | default "OnFailure" }}
          {{- with .Values.generator.nodeSelector }}
          nodeSelector:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.generator.affinity }}
          affinity:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.generator.tolerations }}
          tolerations:
          {{- toYaml . | nindent 8 }}
          {{- end }}
          volumes:
            - name: {{ include "awwesome.fullname" . }}-volume
              persistentVolumeClaim:
                claimName: {{ include "awwesome.fullname" . }}-pvc
